/////////////////////////////////////////////////////////////////////////
//
// © University of Southampton IT Innovation Centre, 2013
//
// Copyright in this software belongs to University of Southampton
// IT Innovation Centre of Gamma House, Enterprise Road, 
// Chilworth Science Park, Southampton, SO16 7NS, UK.
//
// This software may not be used, sold, licensed, transferred, copied
// or reproduced in whole or in part in any manner or form or in or
// on any media by any person other than in accordance with the terms
// of the Licence Agreement supplied with the software, or otherwise
// without the prior written consent of the copyright owners.
//
// This software is distributed WITHOUT ANY WARRANTY, without even the
// implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
// PURPOSE, except where stated in the Licence Agreement supplied with
// the software.
//
//      Created By :            Simon Crowle
//      Created Date :          29-Sep-2013
//      Created for Project :   EXPERIMEDIA
//
/////////////////////////////////////////////////////////////////////////

package uk.ac.soton.itinnovation.experimedia.arch.ecc.samples.simplePROVECCClient;

import javax.swing.JComboBox;

/**
 *
 * @author Simon Crowle
 */
public class ClientView extends javax.swing.JFrame {

  private ClientViewListener clientViewListener;
  
  /**
   * Creates new form ClientView
   */
  public ClientView( ClientViewListener cvl ) {
    
    clientViewListener = cvl;
    
    initComponents();
    
    // Don't auto-select items
    subjectCB.setSelectedItem( null );
    activityCB.setSelectedItem( null );
    objectCB.setSelectedItem( null );
  }

  /**
   * This method is called from within the constructor to initialise the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    sendPROVButton = new javax.swing.JButton();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    subjectCB = new javax.swing.JComboBox();
    activityCB = new javax.swing.JComboBox();
    objectCB = new javax.swing.JComboBox();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Simple ECC PROV Client");
    setMaximumSize(null);
    setMinimumSize(null);
    setName("PROVUIFrame"); // NOI18N
    setResizable(false);
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowClosed(java.awt.event.WindowEvent evt) {
        onViewClosed(evt);
      }
      public void windowClosing(java.awt.event.WindowEvent evt) {
        formWindowClosing(evt);
      }
    });

    jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jLabel1.setText("PROV Client demo");

    sendPROVButton.setText("Send PROV sample");
    sendPROVButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        onSendPROVSample(evt);
      }
    });

    jLabel2.setText("Agent");

    jLabel3.setText("Activity");

    jLabel4.setText("Entity");

    subjectCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Alice", "Bob", "Carol" }));
    subjectCB.setMinimumSize(new java.awt.Dimension(50, 18));
    subjectCB.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        onSubjectSelected(evt);
      }
    });

    activityCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Play", "Pause", "Stop" }));
    activityCB.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        onPredicateSelected(evt);
      }
    });

    objectCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Video A", "Video B", "Video C" }));
    objectCB.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        onObjectSelected(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(19, 19, 19)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(143, 143, 143)
                .addComponent(jLabel3))
              .addGroup(layout.createSequentialGroup()
                .addComponent(subjectCB, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(sendPROVButton, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(activityCB, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel4)
              .addComponent(objectCB, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
        .addContainerGap(21, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel2)
          .addComponent(jLabel3)
          .addComponent(jLabel4))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(subjectCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(activityCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(objectCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
        .addComponent(sendPROVButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void onViewClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_onViewClosed
   
    
  }//GEN-LAST:event_onViewClosed

  private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    
    clientViewListener.onClientViewClosed();
  }//GEN-LAST:event_formWindowClosing

  private void onSubjectSelected(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onSubjectSelected
    
    JComboBox cb = (JComboBox) evt.getSource();
    Object selected = cb.getSelectedItem();
    
    if ( selected != null )
      clientViewListener.onAgentSelected( (String) selected );    
  }//GEN-LAST:event_onSubjectSelected

  private void onPredicateSelected(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onPredicateSelected
    
    JComboBox cb = (JComboBox) evt.getSource();
    Object selected = cb.getSelectedItem();
    
    if ( selected != null )
      clientViewListener.onActivitySelected( (String) selected ); 
  }//GEN-LAST:event_onPredicateSelected

  private void onObjectSelected(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onObjectSelected
    
    JComboBox cb = (JComboBox) evt.getSource();
    Object selected = cb.getSelectedItem();
    
    if ( selected != null )
      clientViewListener.onEntitySelected( (String) selected ); 
  }//GEN-LAST:event_onObjectSelected

  private void onSendPROVSample(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onSendPROVSample
    clientViewListener.onSendProvData();
  }//GEN-LAST:event_onSendPROVSample


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JComboBox activityCB;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JComboBox objectCB;
  private javax.swing.JButton sendPROVButton;
  private javax.swing.JComboBox subjectCB;
  // End of variables declaration//GEN-END:variables
}
