#!/bin/bash

set -eux

juju-log "edm relation changed"

relation-set database=eccdashboard

if [ "`relation-get host`" == "" ]; then
	juju-log "Waiting for postgres database..."
	exit 0
fi

cat > /var/lib/tomcat7/edm.properties <<EOF
dbURL = `relation-get host`:5432
dbName = postgres
dbUsername = `relation-get user`
dbPassword = `relation-get password`
dbType = postgresql
EOF

echo `relation-get host`:5432:*:`relation-get user`:`relation-get password` > ~/.pgpass
chmod 0600 ~/.pgpass
psql -w -h `relation-get host` -d postgres -U `relation-get user` -f edm-metrics-postgres.sql

./maybe-restart.sh
