#!/bin/bash

set -eux

juju-log "edm relation changed"

relation-set database=WeGov

if [ "`relation-get host`" == "" ]; then
	juju-log "Waiting for postgres database..."
	exit 0
fi

cat > /var/lib/tomcat7/edm.properties <<EOF
dbURL = `relation-get host`:5432
dbName = `relation-get database`
dbUsername = `relation-get user`
dbPassword = `relation-get password`
dbType = postgresql
EOF

cat > /var/lib/tomcat7/coordinator.properties << EOF
# Properties for WeGov Coordinator

# POSTGRESQL SERVER CONFIGURATION (admin access)
postgres.url=jdbc:postgresql://`relation-get host`:5432/WeGov
postgres.login=`relation-get user`
postgres.pass=`relation-get password`

# POSTGRESQL DATABASES AND SCHEMAS CONFIGURATION
postgres.database.name=WeGov
postgres.database.mgt.name=WeGovManagement
postgres.database.data.name=WeGovRawData

# KMI Analysis
kmi.pathto.datafolder=/Users/max/Documents/Work/wegov/KmiAnalysis/data

# Psuedo user that holds template widgets - when a real user creates a widget
# it is copied from the set of templates held by this template user
wegov.widget.template.source.user=template-widgets
wegov.widget.template.source.user.password=cvbgt543edfr

#optional headsup analysis - do not use
wegov.headsup.enabled=false
wegov.headsup.source.file=./HeadsUp_moderated_and_cleaned_posts.xls

# OAuth tokens for WeGov Test application / wegovtest1 Twitter account
# XXX: external juju relation?
oauthConsumerKey=ZVVDaMt6Bu5n7l161ozRrQ
oauthConsumerSecret=84xQEe9JkjvM0ZedQDHjqAkBMZYjPqoUrqXa7qh895E
oauthConsumerAccessToken=380850453-JEserFePITVZa63nYXiun7bwaOsoJdwYNzi4vMEx
oauthConsumerAccessTokenSecret=JYGZXw2YsdahbVvf782Az2Cj4bO3Yk3VcsNcl6s6AE
EOF

cat > /var/lib/tomcat7/webapps/ROOT/WEB-INF/classes/quartz/quartz.properties << EOF
org.quartz.scheduler.instanceName = theScheduler
org.quartz.threadPool.threadCount = 5
org.quartz.scheduler.skipUpdateCheck=true

#
# Quartz Configuration
#
# Development config
#org.quartz.jobStore.class=org.quartz.simpl.RAMJobStore

# Production config (uncomment to use postgres database)
org.quartz.jobStore.class=org.quartz.impl.jdbcjobstore.JobStoreTX

org.quartz.dataSource.WEGOVDS.driver = org.postgresql.Driver
org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
org.quartz.jobStore.tablePrefix = qrtz_
# N.B. You must ensure that database matches that defined in coordinator.properties!
org.quartz.dataSource.WEGOVDS.URL = jdbc:postgresql://`relation-get host`:5432/`relation-get database`
org.quartz.dataSource.WEGOVDS.user = `relation-get user`
org.quartz.dataSource.WEGOVDS.password = `relation-get password`

# By default Quartz looks like it uses the default schema
# of the login user. In many cases for postgres this is "public".

org.quartz.jobStore.dataSource=WEGOVDS
EOF

java -jar wegov-database-maintenance-1.0-jar-with-dependencies.jar

echo `relation-get host`:5432:`relation-get database`:`relation-get user`:`relation-get password` > ~/.pgpass
chmod 0600 ~/.pgpass
psql -w -h `relation-get host` -d `relation-get database` -U `relation-get user` -f edm-metrics-postgres.sql

psql -U `relation-get user` -d "WeGov" -h `relation-get host` -f tables_postgres.sql

./maybe-restart.sh
