/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package uk.ac.soton.itinnovation.experimedia.arch.ecc.samples.basicECCContainer;

import java.util.UUID;
import javax.swing.*;

/**
 *
 * @author Simon Crowle
 */
public class EMLoginView extends JFrame {
  
  private EMLoginViewListener viewListener;

  /**
   * Creates new form EMLoginView
   */
  public EMLoginView() {
    initComponents();
  }
  
  public void setViewListener( EMLoginViewListener listener )
  { viewListener = listener; }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    titleLabel = new javax.swing.JLabel();
    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    rabbitServerIPField = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    emUUIDField = new javax.swing.JTextField();
    clearEDMCheckBox = new javax.swing.JCheckBox();
    startButton = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("ECC Desktop Container");
    setResizable(false);

    titleLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
    titleLabel.setText("ECC Java Desktop Container");

    jPanel1.setBackground(new java.awt.Color(242, 242, 242));
    jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

    jLabel1.setText("Rabbit Server IP");

    rabbitServerIPField.setText("127.0.0.1");

    jLabel3.setText("Monitor ID (UUID)");

    emUUIDField.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
    emUUIDField.setText("00000000-0000-0000-0000-000000000000");

    clearEDMCheckBox.setText("Clear EDM data at start");

    org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(jPanel1Layout.createSequentialGroup()
            .add(clearEDMCheckBox)
            .add(0, 0, Short.MAX_VALUE))
          .add(jPanel1Layout.createSequentialGroup()
            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
              .add(jLabel1)
              .add(jLabel3))
            .add(37, 37, 37)
            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
              .add(jPanel1Layout.createSequentialGroup()
                .add(emUUIDField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 200, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
              .add(rabbitServerIPField))))
        .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(jLabel1)
          .add(rabbitServerIPField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        .add(9, 9, 9)
        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(jLabel3)
          .add(emUUIDField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 68, Short.MAX_VALUE)
        .add(clearEDMCheckBox)
        .add(15, 15, 15))
    );

    jPanel1Layout.linkSize(new java.awt.Component[] {jLabel1, jLabel3}, org.jdesktop.layout.GroupLayout.VERTICAL);

    startButton.setText("Start ECC Container");
    startButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        onStartButtonClicked(evt);
      }
    });

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(layout.createSequentialGroup()
            .add(95, 95, 95)
            .add(startButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 153, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
          .add(layout.createSequentialGroup()
            .add(60, 60, 60)
            .add(titleLabel))
          .add(layout.createSequentialGroup()
            .addContainerGap()
            .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .addContainerGap(34, Short.MAX_VALUE)
        .add(titleLabel)
        .add(18, 18, 18)
        .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .add(37, 37, 37)
        .add(startButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .add(21, 21, 21))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void onStartButtonClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onStartButtonClicked
    
    String  ip = rabbitServerIPField.getText();
    UUID    id = UUID.fromString( emUUIDField.getText() );
    boolean cl = clearEDMCheckBox.isSelected();
    
    if ( ip == null || id == null )
      JOptionPane.showMessageDialog( this, "Set-up problems",
                                     "Please check IP and ID parameters are valid",
                                     JOptionPane.ERROR_MESSAGE );
    else
      viewListener.onStartECC( ip, id, cl );
  }//GEN-LAST:event_onStartButtonClicked

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JCheckBox clearEDMCheckBox;
  private javax.swing.JTextField emUUIDField;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JTextField rabbitServerIPField;
  private javax.swing.JButton startButton;
  private javax.swing.JLabel titleLabel;
  // End of variables declaration//GEN-END:variables
}
