jquery_lang_js.prototype.lang.de = {
	'WeGov Project':'WeGov Projekt',
	'WeGov Prototype':'WeGov Prototype',
	'WeGov Consortium':'WeGov Konsortium',
	'About':'Über uns',
	'Terms of Use':'Nutzungsbedingungen',
	'Privacy':'Datenschutz',
	'Contact':'Kontakt',
	'Social networking technology provides major new opportunities for policy makers (eGovernment) to engage with the community (eSociety), and this website is the second prototype of a toolset	that allows policy makers (e.g. MPs, representatives of local and national governments) to take full advantage to be taken of a wide range of existing and well established social networking sites in order to engage citizens in two-way dialogs as part of the governance and policymaking processes.':'WeGov – Where eGovernment meets the eSociety ist ein EU-Forschungsprojekt im 7. Forschungsrahmenprogramm. Detaillierte Informationen finden Sie bitte auf unserer Projektseite <a href="http://www.wegov-project.eu/">http://wegov-project.eu</a>.',
	'A key feature of our	approach is to allow policy makers to move away from the limitations inherent in the current practice of using bespoke and dedicated platforms (e.g. specific opinion soliciting websites hosted by governments) and instead make full use of the high levels of participation and rich discussions that already take place in existing social networking communities. In short, use the platforms the citizens use already.':'<br>',
	'WeGov is developing the tools and techniques for closing the loop between policy makers and the citizens, and this website contains a number of configurable tools to perform tasks such as searching on social networking sites and	analysis of the results. The tools are being added to all the time,	and make it possible to detect, track and mine opinions and	discussions on policy oriented topics.':'Das Ziel des WeGov-Projektes ist die Vernetzung von Bürgern mit der Politik durch Soziale Online-Netzwerke wie Twitter und Facebook. Der Ansatz ist die Entwicklung eines Instrumentenkastens für politische Entscheider zur Analyse Sozialer Online-Netzwerke. Die Analyse erfolgt über die im Projekt entwickelte Topic Opinion Analyse sowie die User Behaviour Analyse. Beide Analysen lassen sich zur Identifizierung von relevanten Kommentaren und Nutzern auf Sozialen Online-Netzwerken verwenden. Suchergebnisse lassen sich teilweise geografisch einschränken.',
	'For more information please visit: <a href="http://www.wegov-project.eu/">http://www.wegov-project.eu/</a>':'<br>',
};