#!/bin/bash

set -eu

if [ -f pid ]; then
	juju-log "KILL existing process"
	kill `cat pid` || juju-log "KILL failed"
	rm pid
fi

if [ ! -f em.properties ]; then
	juju-log "Waiting for Rabbit relation to be set up..."
	exit 0
fi

if [ ! -f edm.properties ]; then
	juju-log "Waiting for Posgresql relation to be set up..."
	exit 0
fi

juju-log "START headless client"

cat > headless.log <<EOF
Starting headless client at `date`

em.properties:
`cat em.properties`

edm.properties:
`cat edm.properties`

echo Running Java...
EOF

(echo $$ >> pid && exec java -cp '.:lib/dependency/*:lib/experimedia-arch-ecc-samples-headlessECCClient-1.0-SNAPSHOT.jar' uk.ac.soton.itinnovation.experimedia.arch.ecc.samples.headlessECCClient.EntryPoint) >> headless.log 2>&1 &
