#!/bin/bash

juju-log "localdb relation changed"

relation-set database=headless

if [ "`relation-get host`" == "" ]; then
	juju-log "Waiting for postgres database..."
	exit 0
fi

echo `relation-get host`:5432:`relation-get database`:`relation-get user`:`relation-get password` > ~/.pgpass
chmod 0600 ~/.pgpass
psql -w -h `relation-get host` -d `relation-get database` -U `relation-get user` -f edm-metrics-postgres.sql

cd `dirname $0`/../code

cat > edm.properties <<EOF
dbURL = `relation-get host`:5432
dbName = `relation-get database`
dbUsername = `relation-get user`
dbPassword = `relation-get password`
dbType = postgresql
EOF

./restart
