#!/bin/bash

juju-log "localdb relation changed"

relation-set database=headless

if [ "`relation-get host`" == "" ]; then
	juju-log "Waiting for postgres database..."
	exit 0
fi

cd `dirname $0`/../code

cat > edm.properties <<EOF
dbURL = `relation-get host`:5432
dbName = `relation-get database`
dbUsername = `relation-get user`
dbPassword = `relation-get password`
dbType = postgresql
EOF

./restart
