#!/bin/bash

set -eu

if [ -f pid ]; then
	juju-log "KILL existing process"
	kill `cat pid` || juju-log "KILL failed"
	rm pid
fi

if [ ! -f em.properties ]; then
	juju-log "Waiting for Rabbit relation to be set up..."
	exit 0
fi

juju-log "START headless client"

(echo $$ >> pid && exec java -cp '.:lib/dependency/*:lib/experimedia-arch-ecc-samples-headlessECCClient-0.9-SNAPSHOT.jar' uk.ac.soton.itinnovation.experimedia.arch.ecc.samples.headlessECCClient.EntryPoint) > headless.log 2>&1 &
